[package]
name = "stylize-other-widget"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ratatui.workspace = true
tui-shader.workspace = true
