name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install llvmpipe and lavapipe
      run: |
        sudo apt-get update -y -qq
        sudo add-apt-repository ppa:oibaf/graphics-drivers -y
        sudo apt-get update
        sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
        
    - name: Build
      run: cargo build --verbose
      
    - name: Build examples
      run: cargo build --examples
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run doc tests
      run: cargo test --doc

