name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install llvmpipe and lavapipe
      run: |
        sudo apt-get update -y
        sudo apt-get install -y mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers
        
    - name: Build
      run: cargo build --verbose
      
    - name: Build examples
      run: cargo build --examples
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run doc tests
      run: cargo test --doc

